"""Measured drawings, generated from the room model — plan, blueprint, elevations, isometric.

These are DRAWN, not generated by an image model, so they cannot invent an opening, move a
window or enlarge the room. They are also handed to the renderer as dimensional references,
which is what keeps the photoreal views honest.

Works for any room shape: walls may run at any angle, and elevations are produced for whichever
walls the project asks for.
"""
from __future__ import annotations

import math
import pathlib
import subprocess

INK, MID, LIGHT, PAPER = "#16181d", "#7b8189", "#c8ccd2", "#fbfaf7"
ACCENT, FURN, JOIN = "#a1442c", "#e2ddd2", "#c9b98f"
BLUE_BG, BLUE_LINE, BLUE_FAINT, BLUE_GRID = "#123a63", "#dbe7f3", "#6f93b8", "#1d4c7d"
FONT = "'Helvetica Neue',Helvetica,Arial,sans-serif"


# ---------------------------------------------------------------- svg primitives

def svg(w, h, body, bg=PAPER):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
            f'viewBox="0 0 {w} {h}"><rect width="{w}" height="{h}" fill="{bg}"/>{body}</svg>')


def t(x, y, s, size=11, fill=INK, anchor="start", weight=400, rot=None, ls=0):
    r = f' transform="rotate({rot} {x:.1f} {y:.1f})"' if rot is not None else ""
    s = (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
    return (f'<text x="{x:.1f}" y="{y:.1f}" font-family="{FONT}" font-size="{size}" fill="{fill}" '
            f'text-anchor="{anchor}" font-weight="{weight}" letter-spacing="{ls}"{r}>{s}</text>')


def line(x1, y1, x2, y2, stroke=INK, w=1, dash=None):
    d = f' stroke-dasharray="{dash}"' if dash else ""
    return (f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" stroke="{stroke}" '
            f'stroke-width="{w}"{d}/>')


def rect(x, y, w, h, fill="none", stroke=INK, sw=1, dash=None):
    d = f' stroke-dasharray="{dash}"' if dash else ""
    return (f'<rect x="{x:.1f}" y="{y:.1f}" width="{max(w,0):.1f}" height="{max(h,0):.1f}" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="{sw}"{d}/>')


def poly(pts, fill="none", stroke=INK, sw=1):
    p = " ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
    return f'<polygon points="{p}" fill="{fill}" stroke="{stroke}" stroke-width="{sw}" stroke-linejoin="round"/>'


def path(d_, fill="none", stroke=INK, sw=1, dash=None):
    da = f' stroke-dasharray="{dash}"' if dash else ""
    return f'<path d="{d_}" fill="{fill}" stroke="{stroke}" stroke-width="{sw}"{da}/>'


def dim(x1, y1, x2, y2, label, colour=MID, size=9):
    out = [line(x1, y1, x2, y2, colour, 0.7)]
    ang = math.degrees(math.atan2(y2 - y1, x2 - x1))
    for px, py in ((x1, y1), (x2, y2)):
        out.append(f'<line x1="{px-4:.1f}" y1="{py-4:.1f}" x2="{px+4:.1f}" y2="{py+4:.1f}" '
                   f'stroke="{colour}" stroke-width="0.9" transform="rotate({ang:.1f} {px:.1f} {py:.1f})"/>')
    mx, my = (x1 + x2) / 2, (y1 + y2) / 2
    if abs(ang) > 60:
        out.append(t(mx - 4, my, label, size, colour, "middle", 500, rot=-90))
    else:
        out.append(t(mx, my - 4, label, size, colour, "middle", 500))
    return "".join(out)


def mm(v, units="m"):
    return f"{v*1000:.0f}" if units == "m" else f"{v:.2f}"


# ---------------------------------------------------------------- plan

def draw_plan(room, spec=None, blueprint=False, title=None):
    x0, y0, x1, y1 = room.bbox()
    W, L = x1 - x0, y1 - y0
    S = min(1100 / max(W, .1), 1500 / max(L, .1), 130)
    ml, mt = 140, 120
    ww, hh = int(W * S + ml + 230), int(L * S + mt + 150)

    ink = BLUE_LINE if blueprint else INK
    mid = BLUE_FAINT if blueprint else MID
    bg = BLUE_BG if blueprint else PAPER
    fill_room = "none" if blueprint else "#ffffff"
    f_furn = "none" if blueprint else FURN
    f_join = "none" if blueprint else JOIN

    def px(x, y):
        return ml + (x - x0) * S, mt + (y - y0) * S

    o = []
    if blueprint:
        g = 0.5
        n = int(W / g) + 2
        for i in range(n):
            X, _ = px(x0 + i * g, 0)
            o.append(line(X, mt, X, mt + L * S, BLUE_GRID, 0.6))
        for i in range(int(L / g) + 2):
            _, Y = px(0, y0 + i * g)
            o.append(line(ml, Y, ml + W * S, Y, BLUE_GRID, 0.6))

    o.append(poly([px(*p) for p in room.outline()], fill_room, ink, 3.2))

    # openings, cut through the wall line
    for op in room.openings:
        a, b = room.opening_plan_segment(op)
        (ax, ay), (bx, by) = px(*a), px(*b)
        o.append(line(ax, ay, bx, by, bg, 5.5))
        o.append(line(ax, ay, bx, by, ACCENT if not blueprint else BLUE_LINE, 2.4))
        w = room.wall(op.wall)
        nx, ny = w.inward
        mx, my = (ax + bx) / 2, (ay + by) / 2
        if op.type in ("door", "doorway"):
            r = op.width * S / 2
            o.append(path(f"M {ax:.1f} {ay:.1f} A {r:.1f} {r:.1f} 0 0 1 "
                          f"{ax + nx*r:.1f} {ay + ny*r:.1f}", stroke=mid, sw=0.7, dash="3 3"))
        o.append(t(mx + nx * 16, my + ny * 16 + 4, op.tag, 11,
                   ACCENT if not blueprint else BLUE_LINE, "middle", 700))

    # Fixed features - radiators, vents, flues. Drawn as real hatched objects with their tag,
    # because a radiator the brief says must not be boxed in has to be visible on the plan.
    for f in room.features:
        w = room.wall(f.wall)
        a, b = w.point_at(f.pos - f.width / 2), w.point_at(f.pos + f.width / 2)
        (ax, ay), (bx, by) = px(*a), px(*b)
        nx, ny = w.inward
        dpt = 10.0
        quad = [(ax, ay), (bx, by), (bx + nx * dpt, by + ny * dpt), (ax + nx * dpt, ay + ny * dpt)]
        o.append(poly(quad, "none" if blueprint else "#e9edf1", mid, 1.1))
        for i in range(1, 7):
            t0 = i / 7
            hx, hy = ax + (bx - ax) * t0, ay + (by - ay) * t0
            o.append(line(hx, hy, hx + nx * dpt, hy + ny * dpt, mid, 0.5))
        # sit the tag well clear of any opening tag on the same stretch of wall
        o.append(t((ax + bx) / 2 + nx * (dpt + 30), (ay + by) / 2 + ny * (dpt + 30) + 3,
                   f.tag, 7.5, mid, "middle", 700))

    # fan / ceiling items
    fan = (room.existing or {}).get("fan")
    if fan:
        fx, fy = px(fan["x"], fan["y"])
        r = fan.get("blade_span", 1.2) / 2 * S
        o.append(f'<circle cx="{fx:.1f}" cy="{fy:.1f}" r="{r:.1f}" fill="none" stroke="{mid}" '
                 f'stroke-width="0.8" stroke-dasharray="4 4"/>')
        o.append(t(fx, fy + 4, "FAN", 8, mid, "middle", 600))

    # direction layout
    if spec and spec.get("layout"):
        for it in spec["layout"].get("plan", []):
            X, Y = px(it["x"], it["y"])
            fill = f_join if it.get("kind") == "built" else f_furn
            o.append(rect(X, Y, it["w"] * S, it["d"] * S, fill, ink, 1.3))
            lbl = it.get("label", "")
            if lbl:
                cx, cy = X + it["w"] * S / 2, Y + it["d"] * S / 2 + 3
                rot = -90 if it["d"] > it["w"] * 1.6 else None
                # Fit the text to the box: along the box's long side, shrinking to a floor, and
                # only then spilling outside with a leader. An unreadable plan is a useless plan.
                avail = (it["d"] if rot else it["w"]) * S - 6
                size = 8.0
                while size > 5.2 and len(lbl) * size * 0.64 > avail:
                    size -= 0.4
                if len(lbl) * size * 0.64 <= avail:
                    o.append(t(cx, cy, lbl.upper(), size, ink, "middle", 600, rot=rot, ls=0.3))
                else:
                    lx = X + it["w"] * S + 8
                    anchor = "start"
                    if lx + len(lbl) * 4.6 > ml + W * S:      # would run off the sheet
                        lx, anchor = X - 8, "end"
                    o.append(line(X + it["w"] * S / 2, cy - 3, lx + (4 if anchor == "start" else -4),
                                  cy - 3, mid, 0.6))
                    o.append(t(lx, cy, lbl.upper(), 7.5, ink, anchor, 600, ls=0.3))
        if spec["layout"].get("route"):
            rt = [px(*p) for p in spec["layout"]["route"]]
            o.append(path("M " + " L ".join(f"{a:.1f} {b:.1f}" for a, b in rt),
                          stroke=ACCENT if not blueprint else "#7fd4ff", sw=2.0, dash="7 5"))
            mx, my = rt[len(rt) // 2]
            o.append(t(mx + 8, my, "circulation", 8.5,
                       ACCENT if not blueprint else "#7fd4ff", "start", 600))

    o.append(dim(*px(x0, y0 - 0.45), *px(x1, y0 - 0.45), f"{mm(W, room.units)} overall", mid))
    o.append(dim(*px(x0 - 0.45, y0), *px(x0 - 0.45, y1), f"{mm(L, room.units)} overall", mid))

    ttl = title or (f"{spec['id']} {spec['name']}" if spec else "Existing shell")
    base = mt + L * S + 52
    o.append(line(ml, base, ml + W * S, base, ink, 1.4))
    o.append(t(ml, base - 8, "FLOOR PLAN" + ("  ·  BLUEPRINT" if blueprint else ""),
               13, ink, "start", 700, ls=2.2))
    o.append(t(ml, base + 16, ttl, 11, mid))
    o.append(t(ml, base + 32, f"all dimensions in {'mm' if room.units=='m' else room.units}"
                              f"  ·  {room.name}", 8.5, mid))
    o.append(t(ml + W * S, base - 8, f"{room.area():.1f} m²", 13, ink, "end", 700))
    return svg(ww, hh, "".join(o), bg)


# ---------------------------------------------------------------- elevation

def draw_elevation(room, wid, spec=None):
    w = room.wall(wid)
    H, run = room.ceiling_height, w.length
    S = min(1250 / max(run, .1), 420 / H, 150)
    ml, mt = 130, 100
    ww, hh = int(run * S + ml + 170), int(H * S + mt + 170)

    def px(u, z):
        return ml + u * S, mt + (H - z) * S

    o = [rect(ml, mt, run * S, H * S, "#ffffff", INK, 2.4),
         line(ml - 30, mt + H * S, ml + run * S + 30, mt + H * S, INK, 3.0),
         t(ml - 34, mt + H * S + 14, "FFL", 8.5, MID, "end", 600),
         line(ml - 20, mt, ml + run * S + 20, mt, MID, 0.9, dash="6 4"),
         t(ml - 24, mt + 4, "CEILING", 8.5, MID, "end", 600)]

    for op in room.openings_on(wid):
        a, b = px(op.pos - op.width / 2, op.head), px(op.pos + op.width / 2, op.sill)
        if op.type == "arch":
            r = op.width / 2 * S
            o.append(path(f"M {a[0]:.1f} {b[1]:.1f} L {a[0]:.1f} {a[1]+r:.1f} "
                          f"A {r:.1f} {r:.1f} 0 0 1 {b[0]:.1f} {a[1]+r:.1f} L {b[0]:.1f} {b[1]:.1f}",
                          "#f4f1ea", ACCENT, 2.0))
        else:
            o.append(rect(a[0], a[1], b[0] - a[0], b[1] - a[1], "#f4f1ea", ACCENT, 2.0))
        if op.type == "door":
            xm = (a[0] + b[0]) / 2
            o.append(line(xm, a[1], xm, b[1], ACCENT, 1.0))
        o.append(t((a[0] + b[0]) / 2, b[1] + 16,
                   f"{op.tag}  {mm(op.width, room.units)}×{mm(op.height, room.units)}",
                   8.5, ACCENT, "middle", 600))
        if op.sill > 0:
            o.append(t(b[0] + 6, (a[1] + b[1]) / 2, f"sill {mm(op.sill, room.units)}", 8, MID))

    for f in room.features_on(wid):
        a, b = px(f.pos - f.width / 2, f.z + f.height), px(f.pos + f.width / 2, f.z)
        o.append(rect(a[0], a[1], b[0] - a[0], b[1] - a[1], "#eef1f4", MID, 1.2))
        for i in range(1, 6):
            xx = a[0] + (b[0] - a[0]) * i / 6
            o.append(line(xx, a[1] + 1.5, xx, b[1] - 1.5, MID, 0.6))
        o.append(t((a[0] + b[0]) / 2, a[1] - 5, f.tag, 7.5, MID, "middle", 600))

    # direction elements, derived from the plan so the two can never disagree
    if spec and spec.get("layout"):
        for el in spec["layout"].get("elevations", {}).get(wid) or _derive(room, spec, wid):
            a, b = px(el["u"], el["z"] + el["h"]), px(el["u"] + el["w"], el["z"])
            fill = JOIN if el.get("kind") == "built" else FURN
            o.append(rect(a[0], a[1], b[0] - a[0], b[1] - a[1], fill, INK, 1.4))
            o.append(t((a[0] + b[0]) / 2, (a[1] + b[1]) / 2 + 3, el.get("label", "").upper(),
                       8, INK, "middle", 600, ls=0.3))
            o.append(t((a[0] + b[0]) / 2, b[1] + 12,
                       f'{mm(el["w"], room.units)}w × {mm(el["h"], room.units)}h', 7.5, MID, "middle"))

    o.append(dim(ml, mt + H * S + 50, ml + run * S, mt + H * S + 50, f"{mm(run, room.units)} wall length"))
    o.append(dim(ml - 48, mt, ml - 48, mt + H * S, f"{mm(H, room.units)} floor to ceiling"))

    base = mt + H * S + 92
    o.append(line(ml, base, ml + run * S, base, INK, 1.4))
    o.append(t(ml, base - 8, f"ELEVATION — {w.name}".upper(), 11, INK, "start", 700, ls=1.4))
    ttl = f"{spec['id']} {spec['name']}" if spec else "Existing shell"
    o.append(t(ml, base + 16, f"{ttl}  ·  wall {w.id}  ·  viewed square-on from inside the room",
               8.5, MID))
    return svg(ww, hh, "".join(o))


def _derive(room, spec, wid):
    """Elevation elements inferred from the plan layout, for any wall angle."""
    out = []
    for it in spec.get("layout", {}).get("plan", []):
        hit = room.nearest_wall(it)
        if hit and hit[0].id == wid and hit[2] >= room.MIN_RUN:
            out.append({"u": hit[1], "w": hit[2], "z": it.get("z", 0.0),
                        "h": it.get("h", 0.45), "label": it.get("label", ""),
                        "kind": it.get("kind", "")})
    return out


# ---------------------------------------------------------------- isometric

def draw_iso(room, spec=None, hide=None):
    """Dollhouse cutaway. `hide` lists wall ids to omit so you can see in."""
    hide = set(hide or [])
    H = room.ceiling_height
    ww, hh = 1240, 980
    pad, foot = 90, 130
    ca, sa = math.cos(math.radians(30)), 0.62

    def raw(x, y, z):
        return (x - y) * ca, (x + y) * sa - z

    pts = room.outline()
    corners = [(x, y, z) for x, y in pts for z in (0, H)]
    rx = [raw(*c)[0] for c in corners]
    ry = [raw(*c)[1] for c in corners]
    S = min((ww - 2 * pad) / max(max(rx) - min(rx), .1),
            (hh - pad - foot) / max(max(ry) - min(ry), .1))
    ml = pad - min(rx) * S + ((ww - 2 * pad) - (max(rx) - min(rx)) * S) / 2
    mt = pad - min(ry) * S

    def p3(x, y, z):
        sx, sy = raw(x, y, z)
        return ml + sx * S, mt + sy * S

    def quad(a, b, c, d, fill, stroke=INK, sw=1.2):
        return poly([p3(*a), p3(*b), p3(*c), p3(*d)], fill, stroke, sw)

    o = [poly([p3(x, y, 0) for x, y in pts], "#efe7dd", INK, 1.6)]

    for w in room.walls:
        (ax, ay), (bx, by) = w.p0, w.p1
        if w.id in hide:
            o.append(quad((ax, ay, 0), (bx, by, 0), (bx, by, H), (ax, ay, H), "none", LIGHT, 0.8))
            continue
        shade = "#f7f5f0" if abs(w.angle) % math.pi < 0.1 else "#eeece6"
        o.append(quad((ax, ay, 0), (bx, by, 0), (bx, by, H), (ax, ay, H), shade))

    for op in room.openings:
        a, b = room.opening_plan_segment(op)
        fill = "#dfe6ee" if op.wall not in hide else "none"
        o.append(quad((*a, op.sill), (*b, op.sill), (*b, op.head), (*a, op.head), fill, ACCENT, 1.4))
        mxy = ((a[0] + b[0]) / 2, (a[1] + b[1]) / 2)
        xx, yy = p3(*mxy, op.head + 0.12)
        o.append(t(xx, yy, op.tag, 10, ACCENT, "middle", 700))

    # Painter's algorithm: in this projection screen-depth grows with (x + y), so the FAR
    # items are the ones with the smallest sum and must be drawn first. Ties broken by height so
    # a rug never paints over the bookcase standing on the same spot.
    items = sorted(spec.get("layout", {}).get("plan", []) if spec else [],
                   key=lambda i: (i["x"] + i["w"] / 2 + i["y"] + i["d"] / 2,
                                  i.get("z", 0) + i.get("h", 0.45)))
    for it in items:
        x, y, w_, d_ = it["x"], it["y"], it["w"], it["d"]
        z0 = it.get("z", 0.0)
        z1 = z0 + it.get("h", 0.45)
        built = it.get("kind") == "built"
        top = "#ddcfa8" if built else "#efe8da"
        side = "#b3a37b" if built else "#c2b9a6"
        base = "#c9b98f" if built else "#d8cfbe"
        o.append(quad((x, y, z1), (x + w_, y, z1), (x + w_, y + d_, z1), (x, y + d_, z1), top, INK, 1.0))
        o.append(quad((x, y + d_, z0), (x + w_, y + d_, z0), (x + w_, y + d_, z1), (x, y + d_, z1), side, INK, 1.0))
        o.append(quad((x + w_, y, z0), (x + w_, y + d_, z0), (x + w_, y + d_, z1), (x + w_, y, z1), base, INK, 1.0))
        if it.get("label"):
            cx, cy = p3(x + w_ / 2, y + d_ / 2, z1 + 0.06)
            o.append(t(cx, cy, it["label"].upper(), 7.5, INK, "middle", 600, ls=0.3))

    ttl = f"{spec['id']} {spec['name']}" if spec else "Existing shell"
    o.append(line(70, hh - 76, ww - 70, hh - 76, INK, 1.4))
    o.append(t(70, hh - 82, "ISOMETRIC CUTAWAY — DOLLHOUSE VIEW", 13, INK, "start", 700, ls=2.2))
    o.append(t(70, hh - 58, f"{ttl}  ·  near walls removed to show the room", 10, MID))
    tags = ", ".join(op.tag for op in room.openings) or "none"
    o.append(t(70, hh - 42, f"Drawn to scale from the room model. Openings: {tags}. "
                            f"No other opening exists.", 9, MID))
    return svg(ww, hh, "".join(o))


# ---------------------------------------------------------------- output

def rasterise(svg_path, png_path, width=1500):
    """SVG -> PNG via headless Chrome. The SVG is always written; only the raster needs a browser."""
    chrome = next((c for c in ("google-chrome", "chromium", "chromium-browser", "chrome")
                   if subprocess.run(["which", c], capture_output=True).returncode == 0), None)
    if not chrome:
        print(f"    note: no Chrome/Chromium found - wrote {pathlib.Path(svg_path).name} "
              f"but could not rasterise it to PNG", flush=True)
        return False
    txt = pathlib.Path(svg_path).read_text()
    w = int(txt.split('width="')[1].split('"')[0])
    h = int(txt.split('height="')[1].split('"')[0])
    html = pathlib.Path(svg_path).with_suffix(".html")
    html.write_text(f'<html><body style="margin:0">{txt}</body></html>')
    subprocess.run([chrome, "--headless", "--disable-gpu", "--no-sandbox", "--hide-scrollbars",
                    f"--force-device-scale-factor={width/w:.4f}", f"--window-size={w},{h}",
                    f"--screenshot={png_path}", html.as_uri()], capture_output=True)
    html.unlink(missing_ok=True)
    return pathlib.Path(png_path).exists()


def build(project, spec=None, stem="_shell"):
    room = project.room()
    out = project.path / "drawings"
    out.mkdir(parents=True, exist_ok=True)
    elev_walls = project.get("deliverables.elevations") or [w.id for w in room.walls]
    hide = project.get("deliverables.iso_hide_walls") or []

    jobs = [(f"{stem}-plan", draw_plan(room, spec, False), 1500),
            (f"{stem}-blueprint", draw_plan(room, spec, True), 1500),
            (f"{stem}-iso", draw_iso(room, spec, hide), 1600)]
    for wid in elev_walls:
        jobs.append((f"{stem}-elev-{wid}", draw_elevation(room, wid, spec), 1500))

    made = []
    for name, content, w in jobs:
        p = out / f"{name}.svg"
        p.write_text(content)
        png = out / f"{name}.png"
        rasterise(p, png, w)
        made.append(png.name)
    return made
